#security:
#  oauth2:
#    client:
#      clientId: 233668646673605
#      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me
security:
  oauth2:
    client:
      clientId: someClientId
      clientSecret: someClientPwSecret
      accessTokenUri: https://alderheytest.eu-gb.mybluemix.net/oauth/token 
      userAuthorizationUri: https://alderheytest.eu-gb.mybluemix.net/oauth/authorize
      preEstablishedRedirectUri: http://localhost:8080/login
      registeredRedirectUri: http://localhost:8080/login
      useCurrentUri: false

#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form

    resource:
      jwt:
        keyValue: |
           -----BEGIN PUBLIC KEY-----
           MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
           -----END PUBLIC KEY-----
#         key-uri: https://alderheytest.eu-gb.mybluemix.net/oauth/token_key
#      userInfoUri: https://graph.facebook.com/me
